sudo: required
services:
- docker

language: java
jdk:
- oraclejdk8

env:
  global:
  - COMMIT: "${TRAVIS_COMMIT::6}"
  - secure: HUqvDeb8fPJy+CnpR9ASZfTLQlkDcIB65OIn/4IxOtlRL3xEwHdllD/8B77DYmri4VXAKYjfRCr5mN3EPmrVE4l/xEcMN3HganqBSLlKnQuexHoRKDWR+dzXM73fv4Oi8bntnhYEsLu0mHSSN57pIqYfrreXu4xGjoFg53feLARiBqHT6vahi4mlkaF4CMBvQ0YX42k2yialWvqeYKZjSqC8YgYnVNAR/RtQ+qgQhGL/TiSCsizAUkfte3rIq6aob9z2PcbwTOe5SHSFyS5CgJ1bwOY2kyH1Ls7PcFgmoqV8pn4NSGdxxJd0FHm2SqP13gNyKHW5KUEZbz3mHd1tMzJf80XcgGafaug5L0gEktsDwk4ThDMjRw1HXK6MXOt4Ma3cTn3G4pVrBNwUoi4otcUuM0MxiUToNGRFV/v6qbteh9gB9HC3wIb26PDWvTP77tLfSmaTm+9r3s71M+YudIh+7+VXCrPpcwEBLYvi0QqCsReJtxWdCV6fGWxBiq6ZDFj6EaJwx4nhU9DANKnPWahsUNntJtbhqEvv2RI4GVSTBWGXMx19QQ+Ot988Z7a4hUbS+W8s6/FiFbIlMjlsS7LEq5HDJ5e4wn0wIkLSFW7s/3r9YmGN/vZTxDn9Jdq9w0C76n27C3KS4780ZoUuBoNA9YknzcczL1xs8i79C1o=
  - secure: k8DZf70bxKCTdTEEndX2UtP66iVns2U9hY2+x/gb3QKBz51gSpqTSXrn5G2c5QrHSyI9HG8EGHPABTSvcFiRSEkrZSiGN2kLHsNpRnWMf+ix1zqwjw9YW85IBjsN3C4gUPRPN5rmjlr5bHnAfaqjUwM9JfYz38RM/jeJhNHHKEuw/Urutf2TKz6h5HLrR157RY/aZz2W9olg/4BKjg+WNrj1cH9IOWPPqeAkXY3APwnwuYlhGGSM771qDINOJeGtmG9hIxzKuI4P2LzJm6RZ+p9hTDwQfkiGGWt7o//sHIIC88+SxNS3Tn2CRbrMLTIRnfi5zUY0Ib4Ox41DvkpJM7Necz1bMer9gyc55fXGnxhYvE7ceKegyYKcREcKinECpw5UHGU62Q1cCYSAI2i+soL9scfRKlSDqbfFza2e39SAC9mFmuaRE/D/nKPaMEDo98lfR4bzaYizaqOBPgNE+b61ioupaH6qMJTy2z7FuoRyYDHxsnczmhWd+lbEgyr6cM48tyFaSHLvlu8yY00fWlWjGzK+9safwK3T08GL4nvT/Y0XU7jWQpkgxtWbdYACBzshF3Ro5ryMQ4lHIrYdkJtGY1WLDgoq5+WPGNK5ZLkvxLXxqBkpXCwT6mnGy9o/N2ZTvQ2bLrj/PcKK32FM7tgojp3NbNhbDOexMBap2P0=
  - secure: kY4Uvm8P+Velk2a3PRQioXieJVMP0uIRZ+NmMsDQfNUa/QuVMr1FV0yeW1z2R37GKamETLLZ+z7mr9el+nJqsj+M0rGbSn2urnDe9uWAwwv7Fq6nFY+JwiRlFvGm9MYiJYhKitRfRdZEQDEsS+scviBfKm4oNckC6HTMdiEylelWBQsiLVm5KMynQKc1gAbE5HTH55OZIbl7zLAxVOFGHO0cgiaatGKURJ3S8pJWC+NSZw3OXjWJKbBrnLW6fJ/f8SUn/wR+ajfPKUB1gh3+gjVpEsoxssZ9b3x+oIftb/4AfJ5+Y1YFfCd+Dt09Qbuhtk+o29pe5S5eRD0Gzn5kkuwB56UVy8wqKTtmQGbpX49hs47vAb1EywIUtAC251NGurgwyZbH7Mzj5M1SQxwcXDxx7KixhY80qQlpYebGkbndWfca87m9FmmMfgeYOVFb7/0zG+7qCDmRvwgNbUh7fzkBgx5DM9J694Cek0/SkA//K1LRAjK+LyPPiYV7CasnnOk3vSDIk+n5hyKyvSYa7pnNv7Kp7oiHF6gwcCrkMvoS5ap0Px/czdw49yJ6CMI0hjlHiFqXbjtWqwexnmjPdOB0I09/5Ino3GHyRhnjK2IFlGvQbfnj+Pvv5QS+wPJxQmS4PBy/dAQewQqjjr/gGvHhAmHUiNJvsA+VHqjajY8=

addons:
  sonarqube:
    organization: shboland-key
  sonar:
    token:
      secure: DmOd7Ny2y/VqjIZLsbqiAzD+MEU5vTHkD6utgQbOMHpuqhg7QTh7SSnQZOjk1Z9fdABNWnFcPe5iZB6jJXMxP/nU42/K6Bi9itDVipLVQda/RmUqIXL+Htzes705MCqgGMKrPMO5+SxjYC6OkJsfZrGK0qtzR0R7lLo9OFss09ZXivroQHbu8i0LbflsqCubv7Yj4gNthJBLNhQpat0V/cp9cE7Dyk1RfGGqwRUziswdbsseAHihJbl5QbIwFHa/r/XrU+tli1Yf5c6HC01GrZ3QAQFAob9fQsfImbimjU01JLaDoC0yYPq2CAyjUbZqUdk2xG+tYPlTdpkP4kD6U6AzuF3JNcDLkIK8Yr7xzZXB8ALGNTLWa6DdXnbaK2fR0KHC5pv9K7PG9OdcmqzjhXYn2GC6INI6wYAq0epE1FylfV7GmVezX03ilue+ghpo6RXSm0WbWD1k8Xu8LDbdbl7eaXExXalWlazWC7hMr48miBG7g/bnIn3EV0yHlT5P+PnkX8jixu6POGMFaXCDy8AviyLXjqivvxsTB1BrFVKs/YKfJLynfgMBL6w0ehO2U7mYvItjYC3eP9EzEq4bj/GqJedBcSRQHwh3C37HfOVyZdM9Wj8TSUG0OJWKhiGAA0Y4KSP0OG9IRlbQxwW+SbxOLcUv2PGhxwZ4BHzLXjU=

cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.sonar/cache"

install:
- mvn dependency:go-offline

script:
- mvn verify site sonar:sonar -Dmaven.test.failure.ignore=true
- mvn clean install

after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- docker push shboland/inventory-service
