sudo: required

services:
- docker

language: java
jdk:
- oraclejdk8

env:
  global:
  - COMMIT: "${TRAVIS_COMMIT::6}"
  - secure: "HUqvDeb8fPJy+CnpR9ASZfTLQlkDcIB65OIn/4IxOtlRL3xEwHdllD/8B77DYmri4VXAKYjfRCr5mN3EPmrVE4l/xEcMN3HganqBSLlKnQuexHoRKDWR+dzXM73fv4Oi8bntnhYEsLu0mHSSN57pIqYfrreXu4xGjoFg53feLARiBqHT6vahi4mlkaF4CMBvQ0YX42k2yialWvqeYKZjSqC8YgYnVNAR/RtQ+qgQhGL/TiSCsizAUkfte3rIq6aob9z2PcbwTOe5SHSFyS5CgJ1bwOY2kyH1Ls7PcFgmoqV8pn4NSGdxxJd0FHm2SqP13gNyKHW5KUEZbz3mHd1tMzJf80XcgGafaug5L0gEktsDwk4ThDMjRw1HXK6MXOt4Ma3cTn3G4pVrBNwUoi4otcUuM0MxiUToNGRFV/v6qbteh9gB9HC3wIb26PDWvTP77tLfSmaTm+9r3s71M+YudIh+7+VXCrPpcwEBLYvi0QqCsReJtxWdCV6fGWxBiq6ZDFj6EaJwx4nhU9DANKnPWahsUNntJtbhqEvv2RI4GVSTBWGXMx19QQ+Ot988Z7a4hUbS+W8s6/FiFbIlMjlsS7LEq5HDJ5e4wn0wIkLSFW7s/3r9YmGN/vZTxDn9Jdq9w0C76n27C3KS4780ZoUuBoNA9YknzcczL1xs8i79C1o="
  - secure: "k8DZf70bxKCTdTEEndX2UtP66iVns2U9hY2+x/gb3QKBz51gSpqTSXrn5G2c5QrHSyI9HG8EGHPABTSvcFiRSEkrZSiGN2kLHsNpRnWMf+ix1zqwjw9YW85IBjsN3C4gUPRPN5rmjlr5bHnAfaqjUwM9JfYz38RM/jeJhNHHKEuw/Urutf2TKz6h5HLrR157RY/aZz2W9olg/4BKjg+WNrj1cH9IOWPPqeAkXY3APwnwuYlhGGSM771qDINOJeGtmG9hIxzKuI4P2LzJm6RZ+p9hTDwQfkiGGWt7o//sHIIC88+SxNS3Tn2CRbrMLTIRnfi5zUY0Ib4Ox41DvkpJM7Necz1bMer9gyc55fXGnxhYvE7ceKegyYKcREcKinECpw5UHGU62Q1cCYSAI2i+soL9scfRKlSDqbfFza2e39SAC9mFmuaRE/D/nKPaMEDo98lfR4bzaYizaqOBPgNE+b61ioupaH6qMJTy2z7FuoRyYDHxsnczmhWd+lbEgyr6cM48tyFaSHLvlu8yY00fWlWjGzK+9safwK3T08GL4nvT/Y0XU7jWQpkgxtWbdYACBzshF3Ro5ryMQ4lHIrYdkJtGY1WLDgoq5+WPGNK5ZLkvxLXxqBkpXCwT6mnGy9o/N2ZTvQ2bLrj/PcKK32FM7tgojp3NbNhbDOexMBap2P0="

addons:
  sonarqube:
    organization: shboland-key

cache:
  directories:
  - "$HOME/.m2"

script:
- mvn clean install
- sonar-scanner

after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- docker push shboland/inventory-service
