spring.profiles.active: development
---
spring:
  profiles: development
  datasource:
    url: jdbc:postgresql://localhost:5482/postgres
    username: pgroot
    password: pgpass
liquibase:
  change-log: classpath:/liquibase/db-changelog.xml
eureka:
  client:
    enabled: false
---
spring:
  profiles: test
  datasource:
    url: jdbc:h2:file:~/inventoryDB
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
liquibase:
  change-log: classpath:/liquibase/db-changelog.xml
eureka:
  client:
    enabled: false
---
spring:
  profiles: production
  jpa:
    show_sql: false
    database: POSTGRESQL
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: pgroot
    password: dbpass
liquibase:
  change-log: classpath:/liquibase/db-changelog.xml
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
