spring.profiles.active: development
---
spring:
  profiles: development
eureka:
  client:
    enabled: false
---
spring:
  profiles: production
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
